# Generated by Django 3.2.12 on 2022-03-25 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否是员工')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否是超级管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'userInfo',
            },
        ),
        migrations.CreateModel(
            name='TcCate',
            fields=[
                ('tc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tc_parent_id', models.IntegerField(null=True)),
                ('tc_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'trashCate',
            },
        ),
        migrations.CreateModel(
            name='TcSearch',
            fields=[
                ('sea_info', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sea_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sea_way', models.CharField(default='0', max_length=2)),
                ('sea_cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wx.tccate')),
                ('sea_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seaInfo',
                'ordering': ['-sea_time'],
            },
        ),
    ]
