# Generated by Django 3.2.12 on 2022-04-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
    ]
